paths:
    virtbs_root: /srv/virtbs

address_pool:
        mac_start: '52:54:00:00:00'
        ipv4_start: '172.16.0.0'
        # 16 slices each with 16 maximum network each with maximum ~253 machine
        ipv4_virtbs_prefix: 16  # 255.255.0.0 (not in use)
        ipv4_slice_prefix: 20  # 255.255.240.0
        ipv4_subnet_prefix: 24  # 255.255.255.0
        mac_slice_extra_power: 8  # add 4 bit extra above the nets for the mac pool, just for `ip addressles` interfaces
        # for statless
        # assuming 64 bit sub subnet prefixes
        # The lower bits from first 64 is used speedling as subnet pool
        # It could be a list in the future..
        ipv6_stateless_start: 'fd00:aaaa::0'
        # for dual stack (or with configrive for spcial usage)
        ipv6_from4_start: '0:0:0:0:0:ffff::0'
        bmc_port_pase: 8192
        # options ipv4, ipv4as6, ipv6local, ipv6stateless, ..
        prefered_address: ipv4
        ipv6_stateless_default_enabled: False
        ipv4_address_serving_default_enabled: False

image_flow:
    f30:
        driver: image_download
        url_pattern: http://download.eng.brq.redhat.com/pub/fedora/linux/releases/30/Cloud/x86_64/images/Fedora-Cloud-Base-30-1.2.x86_64.raw.xz
        sha256: 'e34fb3fbbb9e3b4757952cf813da80f2dea4b0d1ca311e2017b62f0c74e376d9'
        compression: xz
        fmt: raw
    ubuntu-19.04:
        driver: image_download
        url_pattern: https://cloud-images.ubuntu.com/disco/20190709.1/disco-server-cloudimg-amd64.img
        sha256: '053b8a12f7efa39527a52deb5071dda2bab2c62844b076bf1dba9f2b70f6943b'
        fmt: qcow2
    opensuse-15.1:
        driver: image_download
        url_pattern: https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.1/images/openSUSE-Leap-15.1-OpenStack.x86_64-0.0.4-Build6.2.qcow2
        sha256: 'c1ad9ba548ee509df414eb2a1f115a83bc1175309580360dedb777d4a76176c6'
        fmt: qcow2
    f30-my:
        driver: image_virt_customize
        base_slot: f30
        script:
           file: virtbs/bscript/my.sh
    ubi-my:
        driver: image_virt_customize
        base_slot: ubuntu-19.04
        script:
           file: virtbs/bscript/my.sh
    suse-my:
        driver: image_virt_customize
        base_slot: opensuse-15.1
        script:
           file: virtbs/bscript/my.sh
    f30-my-pkg:
        driver: image_virt_customize
        base_slot: f30-my
        script:
           file: virtbs/bscript/fedora_os_basepkg.sh
    ubi-my-pkg:
        driver: image_virt_customize
        base_slot: ubi-my
        script:
           file: virtbs/bscript/ubuntu_os_basepkg.sh
    suse-my-pkg:
        driver: image_virt_customize
        base_slot: suse-my
        script:
           file: virtbs/bscript/opensuse_os_basepkg.sh
    f30-dev:
        driver: image_virt_customize
        base_slot: f30-my-pkg
        script_arguments: --git-args ' --depth 16 '
        script:
            file: virtbs/bscript/os-pipgit.sh
    ubi-dev:
        driver: image_virt_customize
        base_slot: ubi-my-pkg
        script_arguments: --git-args ' --depth 16 '
        script:
            file: virtbs/bscript/os-pipgit.sh
    suse-dev:
        driver: image_virt_customize
        base_slot: suse-my-pkg
        script_arguments: --git-args ' --depth 16 '
        script:
            file: virtbs/bscript/os-pipgit.sh

network_flags:
   mynet:
      internet_access: True
      address_serving_4: True
      # stateless
      address_serving_6: False
      preferred_address: ipv4
      mtu: 1500

   net_team_1:
   net_team_2:
      same_bridge: net_team_1

machine_matrix:
    roles:
        # default gate size (but no swap)
        controller:
            memory: 8192
            vcpu: 8
            disable_address_serving: False
            nets: ['mynet', 'data']
            disks:
               disk0:
                  image_slot:
                  image_tag: default
                  size: '40G'
        # small worker
        worker:
            memory: 2048
            vcpu: 2
            disable_address_serving: False
            nets: ['mynet','data']
        # cloud image as is
        plain:
            memory: 8192
            vcpu: 8
            disable_address_serving: False
            nets: [mynet]
        # cloud image with basic tools
        minim:
            memory: 8192
            vcpu: 8
            nets: [mynet]
            disable_address_serving: False
        # image before getting source pypi packages
        osbase:
            memory: 8192
            vcpu: 8
            nets: [mynet]
            disable_address_serving: False
        # multi disk node for swift/ceph
        disk:
            memory: 4096
            vcpu: 2
            nets: [mynet, 'data', 'replicate']
            disable_address_serving: False
            disks:
                disk1:
                  size: '4G'
                disk2:
                  size: '4G'
                disk3:
                  size: '4G'
        # machine needs to be network booted
        pxe_compute:
            memory: 4096
            vcpu: 2
            disable_address_serving: True
            disks:
               disk0:
                  size: '40G'
        # TODO: support for node group connected net appliances

    fedora:
        controller:
            disks:
                disk0:
                    image_slot: f30-dev
        worker:
            disks:
                disk0:
                    image_slot: f30-dev
        plain:
            disks:
                disk0:
                    image_slot: f30
        minim:
            disks:
                disk0:
                    image_slot: f30-my
        osbase:
            disks:
                disk0:
                    image_slot: f30-my-pkg
        disk:
            disks:
                disk0:
                    image_slot: f30-dev

    ubuntu:
        controller:
            disks:
                disk0:
                    image_slot:  ubi-dev
        worker:
            disks:
                disk0:
                    image_slot: ubi-dev
        plain:
            disks:
                disk0:
                    image_slot: ubuntu-19.04
        minim:
            disks:
                disk0:
                    image_slot: ubi-my
        osbase:
            disks:
                disk0:
                    image_slot:  ubi-my-pkg
        disk:
            disks:
                disk0:
                    image_slot: ubi-dev

    opensuse:
        controller:
            disks:
                disk0:
                    image_slot: suse-dev
        worker:
            disks:
                disk0:
                    image_slot: suse-dev
        plain:
            disks:
                disk0:
                    image_slot: opensuse-15.1
        minim:
            disks:
                disk0:
                    image_slot: suse-my
        osbase:
            disks:
                disk0:
                    image_slot:  suse-my-pkg
        disk:
            disks:
                disk0:
                    image_slot:  suse-dev
    passed:
        controller:
            disks:
                disk0:
                    image_tag: passed
        worker:
            disks:
                disk0:
                    image_tag: passed
        plain:
            disks:
                disk0:
                    image_tag: passed
        minim:
            disks:
                disk0:
                    image_tag: passed
        osbase:
            disks:
                disk0:
                    image_tag: passed
        disk:
            disks:
                disk0:
                    image_tag: passed
